build:
  stage: build
  image: quay.io/buildah/stable
  script:
    - buildah login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - buildah bud -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - buildah push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - buildah push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
