name: Docker Image CI

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "shing6326/docker-clair-scanner"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
          install: true

      - name: Build image
        run: docker build -t ${IMAGE_NAME}:${GITHUB_REF##*/} -t ${IMAGE_NAME}:${GITHUB_SHA:0:8} -t ${IMAGE_NAME}:$(date +%Y-%m-%d) -t ${IMAGE_NAME}:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push images
        run: |
          docker push ${IMAGE_NAME}:${GITHUB_REF##*/}
          docker push ${IMAGE_NAME}:${GITHUB_SHA:0:8}
          docker push ${IMAGE_NAME}:$(date +%Y-%m-%d)
          docker push ${IMAGE_NAME}:latest
